### ISSUE TITLE
Unaligned result from walloc(4)

### ISSUE THREAD

**Issue by marcelvanherk** [wingo/walloc#2]
Hi,

A malloc(4) sometimes returns an unaligned pointer. Here is a javascript code snippet and my log:

```
var _outputs   = wasm._malloc(N*4); // calling with N=1, _malloc directly calls malloc
wasm.function(_outputs); // some processing
var HEAP32 = new Int32Array(wasm.memory.buffer);
var _outp = HEAP32[_outputs/4 + j];
var count = HEAP32[_outp/4];
if (count==undefined)  console.log("*** WASM._malloc may be failing ****", _outp, _outputs, N);

```
code.js:1253 *** WASM._malloc may be failing **** NaN 36880450 1
The address in _outputs  (36880450) is not dividable by 4.

It does not seem to occur for malloc of larger amounts.

Compiled with:

clang --target=wasm32 --no-standard-libraries -Wl,--no-entry -Wl,--export-all -fdeclspec -o main.wasm main.c

Can you have a look? Thanks!

Marcel

**Comment by wingo** [comment]
Thanks for the report.  Do you have a standalone test case?

**Comment by wingo** [comment]
I don't really see how the result can be other than 8-byte aligned.  But to check probabilistically I inserted an assertion in the test (https://github.com/wingo/walloc/commit/a93409f5ebd49c875514c5fee30d3b151f7b0882) and made a few million allocations locally, without the assert firing.  Not sure what this could be.

**Comment by marcelvanherk** [comment]
Hi. I sequentially allocated two 4 bytes regions from my webassembly code
after allocating 4 large regions. The second 4 byte region was misaligned.
I can create a test case this weekend if this is not enough. Thanks Marcel

**Comment by wingo** [comment]
Since the granule size is 8 I am at a loss as to how this could happen.  Happy to be proven wrong tho and a test case would really help.

**Comment by marcelvanherk** [comment]
Hi Andy, I retested as well and could not reproduce it. It may have been an
over 2^31 address that was interpreted as negative in JS. I have been able
to reproduce that. Otherwise I think this bug can be closed. Thanks for
your help.

**Comment by wingo** [comment]
No problem, thanks for walking through it -- cheers :)
